### ISSUE TITLE
로고 표시 안됨.

### ISSUE THREAD

**Issue by yoojinwoo12** [navyCarpet/imitated-skin-liberty#10]
![Screenshot_20240324_213314_Chrome](https://github.com/navyCarpet/imitated-skin-liberty/assets/161662484/79ddec6c-275a-4f38-a491-2c3d606ab628)
![Screenshot_20240324_213309_Chrome](https://github.com/navyCarpet/imitated-skin-liberty/assets/161662484/53cdd474-470f-4c96-91f2-7aaaec4b483e)

**Comment by yoojinwoo12** [comment]
milkwiki.enhawiki.kr:3000

**Comment by navyCarpet** [comment]
스킨은 아무 문제 없는데 스킨이 이상하다고 거짓말치고 다니시면 곤란합니다.

**Comment by yoojinwoo12** [comment]
@navyCarpet 
제가 못한거였네요.. 죄송합니다..
