### ISSUE TITLE
다크 모드 기본 설정 추가

### ISSUE THREAD

**Issue by solutionwiki** [navyCarpet/imitated-skin-liberty#12]
더시드 스킨처럼 다크 컨트롤 옵션 추가.

**Comment by navyCarpet** [comment]
다크 컨트롤 옵션이 뭔가요?

**Comment by solutionwiki** [comment]
더시드위키에서 프로필 클릭 후

**Comment by solutionwiki** [comment]
설정 버튼을 누르면 팝업이 떠올릅니다. 
거기 보면 시스템의 다크 모드를 무시하긴가 뭔가가 있는데 그 설정 좀 만들어달라는 의미입니다.

**Comment by navyCarpet** [comment]
결론부터 말해드리자면 이런 설정을 만들 생각은 없습니다.
 1. 일단 더시드엔진의 '시스템의 다크 테마 설정을 가져오지 않기' 설정은 엔진의 기능입니다.
 2. 현재는 삭제된 기능입니다.
 3. 다크모드 또한 엔진의 기능이어야 하지만 현재는 비공식 기능으로 일부 모방하여 스킨에서 작동하고 있습니다.
