### ISSUE TITLE
1줄짜리 댓글은 블라인드되지 않습니다.

### ISSUE THREAD

**Issue by VaniIIaDev** [navyCarpet/imitated-skin-liberty#13]
오류 발생 위키 : 하늘위키 [haneul.wiki](url)

**Comment by navyCarpet** [comment]
일단 스킨의 css는 [namu-theseed/theseed-skin-liberty](https://github.com/namu-theseed/theseed-skin-liberty)와 같으나 더시드엔진은 popover가 body에서 생성되는 반면, imitated-seed-2의 경우 inline에서 생성되기 때문에 이런 현상이 생기고 있습니다.

**Comment by navyCarpet** [comment]
일단 엔진 개발자에게 문의해 보시고 수정하지 않을 예정이라면 overflow 속성을 통해 임시 해결하도록 하겠습니다.

**Comment by blindplus** [comment]
개발자님이 개인 사정 때문에 집중적인 개발이 어렵다 하셨기 때문에 오래 걸릴 것으로 보이니 일단 스킨에서 임시 해결해주시면 감사하겠습니다.

**Comment by blindplus** [comment]
제발 임시로라도 수정해주세요 너무 불편합니다

**Comment by navyCarpet** [comment]
엔진에 문제가 있어서 발생하는 버그라 엔진 개발자에게 먼저 문의를 하라고 말씀드렸는데 문의는 하지도 않고 이러시는지 잘 모르겠네요

**Comment by navyCarpet** [comment]
현재 임시로 수정한 상태이며 엔진에서 수정되기 전까지 유지하도록 하겠습니다.

**Comment by NOAH01112** [comment]
감사합니다
