### ISSUE TITLE
블라인드가 안됩니다.

### ISSUE THREAD

**Issue by yoojinwoo123** [navyCarpet/imitated-skin-liberty#14]
![Screenshot_20240405_162903_Chrome](https://github.com/navyCarpet/imitated-skin-liberty/assets/164730030/fa5236e7-30db-4097-984b-b67ca8d1d8cf)

**Comment by yoojinwoo123** [comment]
위 사진처럼 원본보기 밑이 보이지 안아 블라인드가 안됩니다.

**Comment by navyCarpet** [comment]
duplicated #13
