### ISSUE TITLE
로고 텍스트로 넣었을때 안보입니다.

### ISSUE THREAD

**Issue by blindplus** [navyCarpet/imitated-skin-liberty#15]
ex. `<b>파이위키</b>`를 로고 주소에 넣으면 보이지 않습니다.

**Comment by navyCarpet** [comment]
자세하게 설명해 주시면 감사하겠습니다.

**Comment by blindplus** [comment]
![image](https://github.com/navyCarpet/imitated-skin-liberty/assets/93462843/c95b3e24-99f2-43a6-906b-477d3c23e975)
를 했는데
![image](https://github.com/navyCarpet/imitated-skin-liberty/assets/93462843/3639033a-23ed-4f26-8203-b43b888e130a)
이 이미지처럼 안보입니다.

**Comment by navyCarpet** [comment]
pin issue를 참고하십시오
