### ISSUE TITLE
스킨 자체 기능으로 favicon을 설정할 수 있나요?

### ISSUE THREAD

**Issue by VaniIIaDev** [navyCarpet/imitated-skin-liberty#16]
..

**Comment by navyCarpet** [comment]
가능할 것 같습니다.

**Comment by somewikiuser** [comment]
어떻게 하나요?

**Comment by navyCarpet** [comment]
제가 지금은 테스트를 할 수 있는 환경이 아니라 며칠 뒤에 한 번 테스트 해보고 알려드리겠습니다.

**Comment by navyCarpet** [comment]
**config.json**
`"additional_heads": "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\"> <link rel=\"icon\" href=\"URL\" type=\"image/x-icon\">"`

**Comment by navyCarpet** [comment]
URL 부분에 icon url 입력하시면 되며 스킨에서 favicon 적용은 딱히 권장하지 않습니다.

**Comment by somewikiuser** [comment]
감사합니다
