### ISSUE TITLE
스레드 깨지는 문제가 있습니다.

### ISSUE THREAD

**Issue by ryudian** [navyCarpet/imitated-skin-liberty#2]
![Screenshot_20240208_081426_Chrome](https://github.com/navyCarpet/imitated-skin-liberty/assets/125643405/bd48021d-8d1c-43d0-9907-158d79d934a2)
모바일에서 첫 스레드가 깨지는 문제가 있습니다. 휴대폰 OS는 안드로이드입니다.

**Comment by navyCarpet** [comment]
https://github.com/gdl-blue/imitated-seed-2/blob/2fe33085133318d7d113aa9024105992b7df6390/routes/thread.js#L580
Line add: `<div class="clearfix"></div>`

**Comment by navyCarpet** [comment]
일단 스킨에서 해결을 못하는 건 아니지만 엔진 측에서 수정하는게 효율적이라고 봄
