### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by Rollable** [navyCarpet/imitated-skin-liberty#20]
혹시 Buma 스킨 오류 수정도 가능하신가요?
현재 개발자분께서 바쁘셔서 오류 수정이 지연되고 있는데 Liberty 스킨 오류 수정하시는 것처럼 Buma 스킨 오류로 수정해주실 수 있으신지 어쭤봅니다.

- [라이선스 페이지 오류](https://github.com/LiteHell/theseed-skin-buma/issues/106)
- [페이지 이동 시에 Search(검색) 창 초기화](https://github.com/LiteHell/theseed-skin-buma/issues/107)

**Comment by navyCarpet** [comment]
생각해보겠습니다.
