### ISSUE TITLE
오류인가요?

### ISSUE THREAD

**Issue by yoojinwoo12** [navyCarpet/imitated-skin-liberty#21]
![Screenshot_20240807_171443_Chrome](https://github.com/user-attachments/assets/9d38df4e-c9bc-435e-8da1-e2026bc5becb)

차단 버튼이 작동을 안합니다.

**Comment by navyCarpet** [comment]
따로 구현하지 않았습니다.

**Comment by jeongjo13** [comment]
구현되면 좋겠네요

**Comment by navyCarpet** [comment]
원본 엔진으로는 구현이 어려울 듯 합니다. 커스텀하여 추가하시는 것을 추천드립니다.
