### ISSUE TITLE
로고 문제

### ISSUE THREAD

**Issue by ryudian** [navyCarpet/imitated-skin-liberty#8]
https://wiki.sh-s.org/w/%ED%8C%8C%EC%9D%BC%3A%EC%9D%B4%EA%B1%B0%EC%99%9C%EC%9D%B4%EB%9E%98_Chrome.jpg

모바일에서 위 사진과 같은 문제가 있는 것으로 보입니다..

**Comment by navyCarpet** [comment]
무슨 뜻인지 잘 모르겠습니다. 재현 환경, 사이트 주소를 알려주시면 확인해 보겠습니다.

**Comment by ryudian** [comment]
[https://wiki.sh-s.org](https://wiki.sh-s.org)에 크롬입니다.

**Comment by navyCarpet** [comment]
현재는 이미지와 같은 오류가 확인되지 않으며 지속될 경우 업데이트나 인터넷 환경을 점검해 보시길 바랍니다.
