### ISSUE TITLE
모바일 환경에서 로고가 보이지 않습니다.

### ISSUE THREAD

**Issue by VaniIIaDev** [navyCarpet/imitated-skin-liberty#9]
https://wiki.sh-s.org/w/%ED%8C%8C%EC%9D%BC%3A%EC%9D%B4%EA%B1%B0%EC%99%9C%EC%9D%B4%EB%9E%98_Chrome.jpg
-----------
위 사진과 같이 모바일에서 로고가 표시되지 않는 문제가 있는 듯 합니다.

+이미 Cordelia님께서 이슈를 발제하시긴 했지만, 개발자님께서 잘 이해하시지 못한 것 같아 다시 한번 문의 드립니다.

**Comment by navyCarpet** [comment]
해당 사이트에서 width가 397px 이하인 모바일 웹에서 표시되지 않는 것을 확인했습니다.

**Comment by navyCarpet** [comment]
해당 사이트 관리자에게 문의하여 `skin.liberty.navbar_logo_minimum_width` 값 설정을 요청하시면 됩니다.
